version: "3.5"

services:
    # It sucks that the extend command has been removed in docker-compose 3.x
    unit-test-php-fpm:
        build:
            context: "./images/php-fpm"
        container_name: "unit-test-php-fpm"
        environment:
            - "PHP_INI_SCAN_DIR=:/usr/local/etc/php/custom.conf.d" # Allow users to override configs
            - "TEST_BASEURL"
            - "TEST_DB_HOST"
            - "TEST_DB_NAME"
            - "TEST_DB_USER"
            - "TEST_DB_PASSWORD"
        external_links:
          - "nginx"
        volumes:
            - "unit-test-shared:/shared" # expose php-fpm socket
            - "./logs/php-fpm:/var/log/php-fpm"
            - "./resources/certificates:/usr/local/share/ca-certificates" # Mount extra certificates
            - "./resources/sphinx:/sphinx" # expose sphinx API. We have to do this here because we need to be enable to update the plugin before we can start the container.
            - "./resources/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.conf.d"
            # Sync files that are writable only into the container (much faster using docker-sync with rsync strategy)
            - "sources-sync/:/srv/vanilla-repositories:nocopy"
            # Sync files that are writable in both directions.
            - "../vanilla/conf/:/srv/vanilla-repositories/conf:delegated"
            - "../vanilla/uploads/:/srv/vanilla-repositories/uploads:delegated"

volumes:
    unit-test-shared:
    sources-sync:
        external: true

networks:
    default:
        external:
            name: "vanilla_network"
