FROM nginx:latest
COPY etc/nginx/nginx.conf            /etc/nginx/nginx.conf
COPY etc/nginx/fastcgi.conf          /etc/nginx/fastcgi.conf
COPY etc/nginx/conf.d/default.conf   /etc/nginx/conf.d/default.conf
